language: rust
sudo: required
rust:
- nightly
- beta
- stable
addons:
  postgresql: 9.4
before_script:
- "./.travis/setup.sh"
script:
- cargo test
- cargo test --features "uuid rustc-serialize time unix_socket serde chrono openssl"
